---
name: fish-lsp
description: LSP implementation for the fish shell language
homepage: https://github.com/ndonfris/fish-lsp
licenses:
  - MIT
languages:
  - Fish
categories:
  - LSP
source:
  # renovate:datasource=git-refs
  id: pkg:github/ndonfris/fish-lsp@v1.0.8-3
  build:
    run: |
      npm exec yarn@1 install
bin:
  fish-lsp: node:bin/fish-lsp
