---
name: kulala-ls
description: A minimal language server for HTTP syntax
homepage: https://github.com/mistweaverco/kulala-ls
licenses:
  - MIT
languages:
  - HTTP
categories:
  - LSP

source:
  id: pkg:npm/@mistweaverco/kulala-ls@1.3.0

bin:
  kulala-ls: npm:kulala-ls
